/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppFuentesRouteImport } from './routes/_app/fuentes'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AppDescargasJobIdRouteImport } from './routes/_app/descargas.$jobId'
import { Route as AppDescargasJobIdZipRouteImport } from './routes/_app/descargas.$jobId.zip'
import { Route as AppReporteAnalysisIdIndexRouteImport } from './routes/_app/reporte.$analysisId.index'
import { Route as AppReporteAnalysisIdImprimirRouteImport } from './routes/_app/reporte.$analysisId.imprimir'
import { Route as ApiRasterCoastalCacheKeyFileRouteImport } from './routes/api/raster.coastal.$cacheKey.$file'
import { Route as ApiRasterAnalysisRasterJobIdKindFileRouteImport } from './routes/api/raster.analysis.$rasterJobId.$kind.$file'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFuentesRoute = AppFuentesRouteImport.update({
  id: '/fuentes',
  path: '/fuentes',
  getParentRoute: () => AppRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDescargasJobIdRoute = AppDescargasJobIdRouteImport.update({
  id: '/descargas/$jobId',
  path: '/descargas/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppDescargasJobIdZipRoute = AppDescargasJobIdZipRouteImport.update({
  id: '/zip',
  path: '/zip',
  getParentRoute: () => AppDescargasJobIdRoute,
} as any)
const AppReporteAnalysisIdIndexRoute =
  AppReporteAnalysisIdIndexRouteImport.update({
    id: '/reporte/$analysisId/',
    path: '/reporte/$analysisId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppReporteAnalysisIdImprimirRoute =
  AppReporteAnalysisIdImprimirRouteImport.update({
    id: '/reporte/$analysisId/imprimir',
    path: '/reporte/$analysisId/imprimir',
    getParentRoute: () => AppRoute,
  } as any)
const ApiRasterCoastalCacheKeyFileRoute =
  ApiRasterCoastalCacheKeyFileRouteImport.update({
    id: '/api/raster/coastal/$cacheKey/$file',
    path: '/api/raster/coastal/$cacheKey/$file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRasterAnalysisRasterJobIdKindFileRoute =
  ApiRasterAnalysisRasterJobIdKindFileRouteImport.update({
    id: '/api/raster/analysis/$rasterJobId/$kind/$file',
    path: '/api/raster/analysis/$rasterJobId/$kind/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/fuentes': typeof AppFuentesRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/descargas/$jobId': typeof AppDescargasJobIdRouteWithChildren
  '/descargas/$jobId/zip': typeof AppDescargasJobIdZipRoute
  '/reporte/$analysisId/imprimir': typeof AppReporteAnalysisIdImprimirRoute
  '/reporte/$analysisId/': typeof AppReporteAnalysisIdIndexRoute
  '/api/raster/coastal/$cacheKey/$file': typeof ApiRasterCoastalCacheKeyFileRoute
  '/api/raster/analysis/$rasterJobId/$kind/$file': typeof ApiRasterAnalysisRasterJobIdKindFileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/fuentes': typeof AppFuentesRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/': typeof AppIndexRoute
  '/descargas/$jobId': typeof AppDescargasJobIdRouteWithChildren
  '/descargas/$jobId/zip': typeof AppDescargasJobIdZipRoute
  '/reporte/$analysisId/imprimir': typeof AppReporteAnalysisIdImprimirRoute
  '/reporte/$analysisId': typeof AppReporteAnalysisIdIndexRoute
  '/api/raster/coastal/$cacheKey/$file': typeof ApiRasterCoastalCacheKeyFileRoute
  '/api/raster/analysis/$rasterJobId/$kind/$file': typeof ApiRasterAnalysisRasterJobIdKindFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/fuentes': typeof AppFuentesRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/descargas/$jobId': typeof AppDescargasJobIdRouteWithChildren
  '/_app/descargas/$jobId/zip': typeof AppDescargasJobIdZipRoute
  '/_app/reporte/$analysisId/imprimir': typeof AppReporteAnalysisIdImprimirRoute
  '/_app/reporte/$analysisId/': typeof AppReporteAnalysisIdIndexRoute
  '/api/raster/coastal/$cacheKey/$file': typeof ApiRasterCoastalCacheKeyFileRoute
  '/api/raster/analysis/$rasterJobId/$kind/$file': typeof ApiRasterAnalysisRasterJobIdKindFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/fuentes'
    | '/auth/confirm'
    | '/auth/set-password'
    | '/descargas/$jobId'
    | '/descargas/$jobId/zip'
    | '/reporte/$analysisId/imprimir'
    | '/reporte/$analysisId/'
    | '/api/raster/coastal/$cacheKey/$file'
    | '/api/raster/analysis/$rasterJobId/$kind/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/fuentes'
    | '/auth/confirm'
    | '/auth/set-password'
    | '/'
    | '/descargas/$jobId'
    | '/descargas/$jobId/zip'
    | '/reporte/$analysisId/imprimir'
    | '/reporte/$analysisId'
    | '/api/raster/coastal/$cacheKey/$file'
    | '/api/raster/analysis/$rasterJobId/$kind/$file'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/fuentes'
    | '/auth/confirm'
    | '/auth/set-password'
    | '/_app/'
    | '/_app/descargas/$jobId'
    | '/_app/descargas/$jobId/zip'
    | '/_app/reporte/$analysisId/imprimir'
    | '/_app/reporte/$analysisId/'
    | '/api/raster/coastal/$cacheKey/$file'
    | '/api/raster/analysis/$rasterJobId/$kind/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  ApiRasterCoastalCacheKeyFileRoute: typeof ApiRasterCoastalCacheKeyFileRoute
  ApiRasterAnalysisRasterJobIdKindFileRoute: typeof ApiRasterAnalysisRasterJobIdKindFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fuentes': {
      id: '/_app/fuentes'
      path: '/fuentes'
      fullPath: '/fuentes'
      preLoaderRoute: typeof AppFuentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/descargas/$jobId': {
      id: '/_app/descargas/$jobId'
      path: '/descargas/$jobId'
      fullPath: '/descargas/$jobId'
      preLoaderRoute: typeof AppDescargasJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/descargas/$jobId/zip': {
      id: '/_app/descargas/$jobId/zip'
      path: '/zip'
      fullPath: '/descargas/$jobId/zip'
      preLoaderRoute: typeof AppDescargasJobIdZipRouteImport
      parentRoute: typeof AppDescargasJobIdRoute
    }
    '/_app/reporte/$analysisId/': {
      id: '/_app/reporte/$analysisId/'
      path: '/reporte/$analysisId'
      fullPath: '/reporte/$analysisId/'
      preLoaderRoute: typeof AppReporteAnalysisIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reporte/$analysisId/imprimir': {
      id: '/_app/reporte/$analysisId/imprimir'
      path: '/reporte/$analysisId/imprimir'
      fullPath: '/reporte/$analysisId/imprimir'
      preLoaderRoute: typeof AppReporteAnalysisIdImprimirRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/raster/coastal/$cacheKey/$file': {
      id: '/api/raster/coastal/$cacheKey/$file'
      path: '/api/raster/coastal/$cacheKey/$file'
      fullPath: '/api/raster/coastal/$cacheKey/$file'
      preLoaderRoute: typeof ApiRasterCoastalCacheKeyFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raster/analysis/$rasterJobId/$kind/$file': {
      id: '/api/raster/analysis/$rasterJobId/$kind/$file'
      path: '/api/raster/analysis/$rasterJobId/$kind/$file'
      fullPath: '/api/raster/analysis/$rasterJobId/$kind/$file'
      preLoaderRoute: typeof ApiRasterAnalysisRasterJobIdKindFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDescargasJobIdRouteChildren {
  AppDescargasJobIdZipRoute: typeof AppDescargasJobIdZipRoute
}

const AppDescargasJobIdRouteChildren: AppDescargasJobIdRouteChildren = {
  AppDescargasJobIdZipRoute: AppDescargasJobIdZipRoute,
}

const AppDescargasJobIdRouteWithChildren =
  AppDescargasJobIdRoute._addFileChildren(AppDescargasJobIdRouteChildren)

interface AppRouteChildren {
  AppFuentesRoute: typeof AppFuentesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDescargasJobIdRoute: typeof AppDescargasJobIdRouteWithChildren
  AppReporteAnalysisIdImprimirRoute: typeof AppReporteAnalysisIdImprimirRoute
  AppReporteAnalysisIdIndexRoute: typeof AppReporteAnalysisIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFuentesRoute: AppFuentesRoute,
  AppIndexRoute: AppIndexRoute,
  AppDescargasJobIdRoute: AppDescargasJobIdRouteWithChildren,
  AppReporteAnalysisIdImprimirRoute: AppReporteAnalysisIdImprimirRoute,
  AppReporteAnalysisIdIndexRoute: AppReporteAnalysisIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  ApiRasterCoastalCacheKeyFileRoute: ApiRasterCoastalCacheKeyFileRoute,
  ApiRasterAnalysisRasterJobIdKindFileRoute:
    ApiRasterAnalysisRasterJobIdKindFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
